"""v14_pdo_tables

Revision ID: 22f186264606
Revises: c974f71b6305
Create Date: 2026-05-15 10:05:48.357578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f186264606'
down_revision: Union[str, Sequence[str], None] = 'c974f71b6305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_events', 'payload',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_prod_events_event_type'), table_name='production_events')
    op.drop_index(op.f('ix_prod_events_wo_at'), table_name='production_events')
    op.drop_index(op.f('ix_prod_issues_assignee'), table_name='production_issues')
    op.drop_index(op.f('ix_prod_issues_status'), table_name='production_issues')
    op.add_column('production_orders', sa.Column('aircraft_type', sa.String(length=80), nullable=True))
    op.add_column('production_orders', sa.Column('work_scope', sa.Text(), nullable=True))
    op.add_column('production_orders', sa.Column('omts_memo_no', sa.String(length=40), nullable=True))
    op.add_column('production_orders', sa.Column('deputy_memo_no', sa.String(length=40), nullable=True))
    op.add_column('production_orders', sa.Column('work_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'production_orders', 'work_orders', ['work_order_id'], ['id'])
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('products', 'designation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('products', 'mass',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('products', 'dimensions',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('products', 'blank_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('products', 'blank_dimensions',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('products', 'material_gost',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('products', 'accuracy_class',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('products', 'roughness',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_unique_constraint(None, 'products', ['designation'])
    op.create_foreign_key(None, 'products', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'products', 'product_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'products', 'materials', ['material_id'], ['id'])
    op.alter_column('professions', 'hourly_rates',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_route_steps_status_seq'), table_name='route_steps')
    op.create_foreign_key(None, 'tech_processes', 'users', ['deleted_by'], ['id'])
    op.alter_column('tp_versions', 'data_snapshot',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_wo_items_workshop'), table_name='work_order_items')
    op.drop_index(op.f('ix_work_orders_barcode'), table_name='work_orders')
    op.create_foreign_key(None, 'work_orders', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.create_index(op.f('ix_work_orders_barcode'), 'work_orders', ['barcode'], unique=False)
    op.create_index(op.f('ix_wo_items_workshop'), 'work_order_items', ['current_workshop_id'], unique=False)
    op.alter_column('tp_versions', 'data_snapshot',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'tech_processes', type_='foreignkey')
    op.create_index(op.f('ix_route_steps_status_seq'), 'route_steps', ['status', 'seq'], unique=False)
    op.alter_column('professions', 'hourly_rates',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='unique')
    op.alter_column('products', 'roughness',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'accuracy_class',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'material_gost',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'blank_dimensions',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'blank_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'dimensions',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'mass',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('products', 'designation',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_column('production_orders', 'work_order_id')
    op.drop_column('production_orders', 'deputy_memo_no')
    op.drop_column('production_orders', 'omts_memo_no')
    op.drop_column('production_orders', 'work_scope')
    op.drop_column('production_orders', 'aircraft_type')
    op.create_index(op.f('ix_prod_issues_status'), 'production_issues', ['status'], unique=False)
    op.create_index(op.f('ix_prod_issues_assignee'), 'production_issues', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_prod_events_wo_at'), 'production_events', ['work_order_id', 'at'], unique=False)
    op.create_index(op.f('ix_prod_events_event_type'), 'production_events', ['event_type'], unique=False)
    op.alter_column('production_events', 'payload',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
